# 1.
Cxx=g++
# 2.
CXXFLAGS = -I/usr/local/include/opencv2 -O0 -g3 -Wall -c
# 3.
LIBS =    -L/usr/lib -lpthread -ldl -lm -std=gnu++0x -std=c++0x -lopencv_core -lopencv_imgproc

# 4.
# put the soruce files here example here face.cpp and function.cpp are commom source files used by both targets
MAP2GRAPH_SOURCES = map2graph.cpp
KERNELBUILDER_SOURCES = kernel.cpp

# 5.Object files
MAP2GRAPH_OBJECTS = map2graph.o
KERNELBUILDER_OBJECTS = kernel.o

#6. target excutable
MAP2GRAPH_EXECUTABLE = map2graph
KERNELBUILDER_EXECUTABLE = kernel

.PHONY: all
all: build_map2graph

.PHONY: build_map2graph
build_map2graph: $(MAP2GRAPH_EXECUTABLE)

$(MAP2GRAPH_EXECUTABLE): $(MAP2GRAPH_OBJECTS) $(KERNELBUILDER_OBJECTS)
	@echo 'Building executable:'
	$(CXX) -o $(MAP2GRAPH_EXECUTABLE) $(MAP2GRAPH_OBJECTS) $(LIBS)
	$(CXX) -o $(KERNELBUILDER_EXECUTABLE) $(KERNELBUILDER_OBJECTS) $(LIBS)
	@echo 'Building Finished!'
# for make clean , cleaning all the build forceuly delete all the files generated by the build process
clean:
	rm -rf $(MAP2GRAPH_EXECUTABLE) $(MAP2GRAPH_OBJECTS) $(KERNELBUILDER_EXECUTABLE) $(KERNELBUILDER_OBJECTS)
	@echo 'Clean Finished!'

%.d: %.cpp
	$(CXX) -MM -MF $@ $<

%.o: %.d

-include $(OBJS:.o=.d)
